language: rust
sudo: required
dist: trusty

# run builds for both all the trains
rust:
  - stable
  - nightly
  - beta

before_script:
  - |
      cargo install --git https://github.com/badboy/travis-after-all-rs &&
      export PATH=$HOME/.cargo/bin/:$PATH


script:
  - |
      cargo test
after_success:
  - travis-after-all
