language: rust
sudo: required
dist: trusty

# run builds for both all the trains
rust:
  - stable
  - nightly
  - beta

before_script:
  - |
      export PATH=$TRAVIS_BUILD_DIR/target/debug:$PATH:$PATH


script:
  - |
      cargo test
after_success:
  - travis-after-all

notifications:
    email: false
